#!/bin/bash
# FILENAME:  mpi.sub
#SBATCH --nodes=2                                                                                                                                        
#SBATCH --ntasks-per-node=20  
#SBATCH --exclusive                                                                                                      
#SBATCH -t 00:05:00 
#SBATCH -A scholar

srun --mpi=pmi2 -n 2 ./mpi_count_words 16 `cat input_files_list_3.txt`