#!/bin/bash
# FILENAME:  small_mpi.sub
#SBATCH --nodes=3                                                                                                                                        
#SBATCH --ntasks-per-node=20
#SBATCH --exclusive                                                                                                      
#SBATCH -t 00:05:00 
#SBATCH -A scholar

srun --mpi=pmi2 -n 3 ./small_mpi